import Head from 'next/head'
import { useState, useEffect } from 'react'
import axios from 'axios'

const local = 'http://localhost:5000'
const global = 'https://simple-express-app-tau.vercel.app/'

export default function Home() {
  const [data, setData] = useState('default')

  useEffect(() => {
    axios
    .get(local)
    .then( res => {
      console.log(res)
      setData(res.data)
    })
    .catch( err => {
      console.err(err)
    })
  })
  return (
    <div>
      <Head>
        <title>Simple MERN App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>hello world</h1>
      <h2>{data}</h2>
    </div>
  )
}
